export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_LOADING = "GET_CHARACTERS_LOADING";

export const GET_CHARACTERS_BY_ID_ERROR = "GET_CHARACTERS_BY_ID_ERROR";
export const GET_CHARACTERS_BY_ID_SUCCESS = "GET_CHARACTERS_BY_ID_SUCCESS";
export const GET_CHARACTERS_BY_ID_LOADING  = "GGET_CHARACTERS_BY_ID_LOADING ";


export const GET_CHARACTERS_BY_CATEGORY_ERROR = "GET_CHARACTERS_BY_CATEGORY_ERROR";
export const GET_CHARACTERS_BY_CATEGORY_SUCCESS = "GET_CHARACTERS_BY_CATEGORY_SUCCESS";
export const GET_CHARACTERS_BY_CATEGORY_LOADING  = "GGET_CHARACTERS_BY_CATEGORY_LOADING ";

export const GET_SEARCH_CHARACTERS_ERROR = "GET_SEARCH_CHARACTERS_ERROR";
export const GET_SEARCH_CHARACTERS_SUCCESS = "GET_SEARCH_CHARACTERS_SUCCESS";
export const GET_SEARCH_CHARACTERS_LOADING = "GET_SEARCH_CHARACTERS_LOADING";


export const GET_SEARCH_BY_NAME_ERROR = "GET_SEARCH_BY_NAME_ERROR";
export const GET_SEARCH_BY_NAME_SUCCESS = "GET_SEARCH_BY_NAME_SUCCESS";
export const GET_SEARCH_BY_NAME_LOADING = "GET_SEARCH_BY_NAME_LOADING";


export const CHARACTERS_BY_LIMIT_OFFSET_ERROR = "CHARACTERS_BY_LIMIT_OFFSET_ERROR";
export const CHARACTERS_BY_LIMIT_OFFSET_SUCCESS = "CHARACTERS_BY_LIMIT_OFFSET_SUCCESS";
export const CHARACTERS_BY_LIMIT_OFFSET_LOADING = "CHARACTERS_BY_LIMIT_OFFSET_LOADING";